services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: contacts_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 654321
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
